// <auto-generated />
using System;
using ExamenParcial2_Progra3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenParcial2_Progra3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamenParcial2_Progra3.Models.CategoriaMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CategoriaMeta");
                });

            modelBuilder.Entity("ExamenParcial2_Progra3.Models.Dificultad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Dificultad");
                });

            modelBuilder.Entity("ExamenParcial2_Progra3.Models.EstadoMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EstadoMeta");
                });

            modelBuilder.Entity("ExamenParcial2_Progra3.Models.EstadoTarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EstadoTarea");
                });

            modelBuilder.Entity("ExamenParcial2_Progra3.Models.Meta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaMetaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EstadoMetaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadMetaId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaMetaId");

                    b.HasIndex("EstadoMetaId");

                    b.HasIndex("PrioridadMetaId");

                    b.ToTable("Meta");
                });

            modelBuilder.Entity("ExamenParcial2_Progra3.Models.PrioridadMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PrioridadMeta");
                });

            modelBuilder.Entity("ExamenParcial2_Progra3.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DificultadId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoTareaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetaId")
                        .HasColumnType("int");

                    b.Property<double>("TiempoEstimadoHoras")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DificultadId");

                    b.HasIndex("EstadoTareaId");

                    b.HasIndex("MetaId");

                    b.ToTable("Tarea");
                });

            modelBuilder.Entity("ExamenParcial2_Progra3.Models.Meta", b =>
                {
                    b.HasOne("ExamenParcial2_Progra3.Models.CategoriaMeta", "Categoria")
                        .WithMany("Metas")
                        .HasForeignKey("CategoriaMetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamenParcial2_Progra3.Models.EstadoMeta", "Estado")
                        .WithMany("Metas")
                        .HasForeignKey("EstadoMetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamenParcial2_Progra3.Models.PrioridadMeta", "Prioridad")
                        .WithMany("Metas")
                        .HasForeignKey("PrioridadMetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Estado");

                    b.Navigation("Prioridad");
                });

            modelBuilder.Entity("ExamenParcial2_Progra3.Models.Tarea", b =>
                {
                    b.HasOne("ExamenParcial2_Progra3.Models.Dificultad", "Dificultad")
                        .WithMany("Tareas")
                        .HasForeignKey("DificultadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamenParcial2_Progra3.Models.EstadoTarea", "Estado")
                        .WithMany("Tareas")
                        .HasForeignKey("EstadoTareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamenParcial2_Progra3.Models.Meta", "Meta")
                        .WithMany("Tareas")
                        .HasForeignKey("MetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dificultad");

                    b.Navigation("Estado");

                    b.Navigation("Meta");
                });

            modelBuilder.Entity("ExamenParcial2_Progra3.Models.CategoriaMeta", b =>
                {
                    b.Navigation("Metas");
                });

            modelBuilder.Entity("ExamenParcial2_Progra3.Models.Dificultad", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("ExamenParcial2_Progra3.Models.EstadoMeta", b =>
                {
                    b.Navigation("Metas");
                });

            modelBuilder.Entity("ExamenParcial2_Progra3.Models.EstadoTarea", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("ExamenParcial2_Progra3.Models.Meta", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("ExamenParcial2_Progra3.Models.PrioridadMeta", b =>
                {
                    b.Navigation("Metas");
                });
#pragma warning restore 612, 618
        }
    }
}
